package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;
import java.util.List;
import java.util.Random;

import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.FAKE_USERS_RANDOM;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsersRandom;

public class FakeApiService implements ApiService {

    private List<User> users = generateUsers();

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        return users;
    } // it needs to return the List, so I changed the return type and added a return.

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {
        List<User> tempRandomUsers = generateUsersRandom();//creates a new temp List and retrieves the List from FakeApiServiceGenerator
        Random rand = new Random(); //creates a random object;
        users.add(tempRandomUsers.get(rand.nextInt(tempRandomUsers.size())));//add a random user to the Users list
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        int index = users.indexOf(user); //finds the index of the user to be deleted
        users.remove(index);//deletes the desired user
    }
}
